### PR TITLE
Improve regex in main.c

### PR DESCRIPTION
**Pull request by danyspin97**

### CODE REVIEW

**Comment by jun7** [comment]
Which system having max 255?

**Comment by danyspin97** [comment]
I am using Exherbo Linux with musl as libc and it has this limit.

**Comment by jun7** [comment]
Wow interesting! Thank you for the information.
Though I found what limitation of domain name labels are 1-63. So fixing it to 1-63 is good.

>The port number

Hmm I suggest to use 'h ' prefix template though I don't mind adding only that.

>The 'Handle regcomp failing'

I don't want verbose code. So pleese remove it.

**Comment by danyspin97** [comment]
> I don't want verbose code. So pleese remove it.

Do you mean the `g_print` shall be removed?

**Comment by jun7** [comment]
The commit 'Handle regcomp failing'

**Comment by danyspin97** [comment]
I had a segmentation fault without that commit with the unfixed regex, is it a good idea to leave unsafe code?

**Comment by jun7** [comment]
Does not the 'Add port support in domain regex' fix the regex?

**Comment by danyspin97** [comment]
> Does not the 'Add port support in domain regex' fix the regex?

Yea, it does. Are you sure it won't crash anymore? Imho that check is needed and doesn't add overhead at all.

**Comment by jun7** [comment]
The check solves anything but only be infomation. We have to fix the args at all because the args are static values.
Did not the segfault info tell you what it happens around regex? Do we need more info?

As you can see wyeb keeps cheap code because it is easy to find bugs in cheap code. I don't say this approach is right though.

**Comment by danyspin97** [comment]
>  We have to fix the args at all because the args are static values.

Can you assure it won't segfaults again? Regcomp return a value just for this check.

>  Did not the segfault info tell you what it happens around regex? Do we need more info?

No, it did not. I had to dig all the code before finding where the segfault happened. If you are using packaged wyeb, you would often lack debug info, and finding bugs is really hard this way.

**Comment by jun7** [comment]
Do you know stack trace?

**Pull request closed without merging**
